on: [ push, pull_request ]

jobs:
    deployment_keys_demo:
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup key
                uses: ./
                with:
                    ssh-private-key: ${{ secrets.MODULE_SSH_KEY }}
            -   run: |
                    for repo in `grep .git main.tf | awk -F "=" '{ print $2 }' | awk -F " '{ print $1 }' `
                     do 
                      echo $repo
                      # git clone $repo test-1-http
                       #cd test-1-http
                       #terraform init
                     done
