on: [ push, pull_request ]

jobs:
    deployment_keys_demo:
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup key
                uses: ./
                with:
                    ssh-private-key: ${{ secrets.MODULE_SSH_KEY }}
            -   run: |
                      mkdir -p ~/terraform-modules/                      
                      git clone https://github.com/rajvasupilli/terraform-modules.git terraform-modules
                      terraform init
                     
